### ISSUE TITLE
Negative Delay Values

### ISSUE THREAD

**Issue by ben-neale** [burnworks/tailwindcss-animation-delay#1]
Installed this today and like it very much. However I needed negative delay values for a looping slideshow. I couldn't see support for this in the instructions, so I tried setting up the way Tailwind handles custom negative values for z-index etc and it didn't work. For starters, I was expecting to see:

`-animation-delay-7000`

but what it produced was

`animation-delay--7000`:

This is what I put in tailwind.config.js:

```
      animationDelay: {
        "-3500": "-3500ms",
        "-7000": "-7000ms",
      },
```

**Comment by burnworks** [comment]
Sorry for the late response.
In version 2.0.0, we now support negative values, so I'd appreciate it if you could give it a try. For more details, please check the `README.md`.

Thanks!
